# Generated by Django 4.2.1 on 2023-05-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
